### ISSUE TITLE
Bugs in the packaging

### ISSUE THREAD

**Issue by rasjani** [Nicceboy/python-markdown-generator#3]
Just going thru the project and noticed following:

1) Example in readme  says:

 ```from markdowngenerator import MarkdownGenerator``` 

This triggers following error:

```
>>> from markdowngenerator import MarkdownGenerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MarkdownGenerator' from 'markdowngenerator' (/Users/rasjani/src/omat/ghteststatus/venv/lib/python3.9/site-packages/markdowngenerator/__init__.py)
```

2) To get rid of that, changing the import from `MarkdownGenerator` to all lowercase, bypasses above issue but then:

```
>>> from markdowngenerator import markdowngenerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rasjani/src/omat/ghteststatus/venv/lib/python3.9/site-packages/markdowngenerator/markdowngenerator.py", line 10, in <module>
    from .config.syntax import (
ModuleNotFoundError: No module named 'markdowngenerator.config'
>>>
```

**Comment by butterpear** [comment]
I am encountering the same issue while working within a Poetry environment. On the brink of despair, the only way to make this work was by placing the folder `markdowngenerator` from this repository to the same level as my executed code and importing it as `from markdowngenerator.markdowngenerator import MarkdownGenerator`. 

However, it would be nice if this could be fixed in the future. ☺️

**Comment by Nicceboy** [comment]
Hey, it is fixed on master now.

I might reserve some time for maintaining this project in the future, as it has got more users than originally expected.

Edit: also the missing setup.py modification is now included there.
